version: '3.8'
services:
  web1:
    build: ./src
    volumes:
      - ./src:/app
    environment:
      SERVER_ID: SERVER-1
    networks:
      - mynetwork
    ports:
      - "8011:8000"

  web2:
    build: ./src
    volumes:
      - ./src:/app
    environment:
      SERVER_ID: SERVER-2
    networks:
      - mynetwork
    ports:
      - "8012:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web1
      - web2
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge  